# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, arcanist, libphutil, php }:

stdenv.mkDerivation rec {
  name = "phabricator-${version}";
  version = "2016-08-12";

  src = fetchgit {
    url = "https://github.com/phacility/phabricator.git";
    rev = "435f756414e692ad02204bf6cb8f185042cec344";
    sha256 = "1zw65p2jgkqym7qi61kx121iw9m74lxrrxxxd06j5600y58fqr3r";
  };

  buildInputs = [ php arcanist libphutil ];

  patches = [ ./conf.patch ];

  installPhase = ''
    mkdir -p $out/libexec
    cp -R . $out/libexec/phabricator
    ln -s ${libphutil}/libexec/libphutil $out/libexec/libphutil
    ln -s ${arcanist}/libexec/arcanist $out/libexec/arcanist
  '';

  meta = {
    description = "A collection of web applications which help software companies build better software";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
