# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, arcanist, libphutil, php }:

let
  phabricator-npm = import ./phabricator-npm.nix {};
in
stdenv.mkDerivation rec {
  name = "phabricator-${version}";
  version = "2016-10-16";

  src = fetchgit {
    url = "https://github.com/phacility/phabricator.git";
    rev = "c9cc3832912f9c52ec1ea1397c062cc3f8ffc659";
    sha256 = "048xb155hxm5iqc8wlx64sl3lcn2m423l1mlw3p1g315if1223va";
  };

  buildInputs = [ php arcanist libphutil phabricator-npm.package ];

  patches = [ ./conf.patch ];

  installPhase = ''
    mkdir -p $out/libexec
    cp -R . $out/libexec/phabricator
    ln -s ${libphutil}/libexec/libphutil $out/libexec/libphutil
    ln -s ${arcanist}/libexec/arcanist $out/libexec/arcanist
    ln -s ${phabricator-npm.package}/lib/node_modules/phabricator-npm/node_modules $out/libexec/phabricator/support/aphlict/server/node_modules
  '';

  meta = {
    description = "A collection of web applications which help software companies build better software";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
