# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, arcanist, libphutil, php }:

let
  phabricator-npm = import ./phabricator-npm.nix {};
in
stdenv.mkDerivation rec {
  name = "phabricator-${version}";
  version = "2016-11-01";

  src = fetchgit {
    url = "https://github.com/phacility/phabricator.git";
    rev = "bd256e9f3fdbb74db78ff994925402cee9d26759";
    sha256 = "0la62k57ck9wmd8mh8p4x1nrnscqqkqj0b4nj270xlbm8kavmy3v";
  };

  buildInputs = [ php arcanist libphutil phabricator-npm.package ];

  patches = [ ./conf.patch ];

  installPhase = ''
    mkdir -p $out/libexec
    cp -R . $out/libexec/phabricator
    ln -s ${libphutil}/libexec/libphutil $out/libexec/libphutil
    ln -s ${arcanist}/libexec/arcanist $out/libexec/arcanist
    ln -s ${phabricator-npm.package}/lib/node_modules/phabricator-npm/node_modules $out/libexec/phabricator/support/aphlict/server/node_modules
  '';

  meta = {
    description = "A collection of web applications which help software companies build better software";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
