# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, flex, makeWrapper, php }:

stdenv.mkDerivation rec {
  name = "libphutil-${version}";
  version = "2016-10-16";

  src = fetchgit {
    url = "https://github.com/phacility/libphutil.git";
    rev = "dd02a0817366bf78d7e468143fbac0e42db7d7c7";
    sha256 = "1svr85dbi7qbblxiy9kmsxasq2yhmw4rjfnmnfdcfwgq459l62q9";
  };

  buildInputs = [ php makeWrapper flex ];

  unpackPhase = "true";
  buildPhase = ''
    ORIG=`pwd`
    cp -R $src libphutil
    chmod +w -R libphutil
    cd libphutil/support/xhpast
    make clean all install
    cd $ORIG
  '';
  installPhase = ''
    mkdir -p $out/libexec
    cp -R libphutil $out/libexec/libphutil
  '';

  meta = {
    description = "Utility library for Phabricator";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
