# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, flex, makeWrapper, php }:

stdenv.mkDerivation rec {
  name = "libphutil-${version}";
  version = "2016-05-16";

  src = fetchgit {
    url = "https://github.com/phacility/libphutil.git";
    rev = "a51a8b98305e08b220972483698ae6f50e77768f";
    sha256 = "0dhf2n42qf1dnp6whhfcqf6pllxhfpfv77r5irzjndirp0j1z9kn";
  };

  buildInputs = [ php makeWrapper flex ];

  unpackPhase = "true";
  buildPhase = ''
    ORIG=`pwd`
    cp -R ${libphutil} libphutil
    chmod +w -R libphutil
    cd libphutil/support/xhpast
    make clean all install
    cd $ORIG
  '';
  installPhase = ''
    mkdir -p $out/libexec
    cp -R libphutil $out/libexec/libphutil
  '';

  meta = {
    description = "Utility library for Phabricator";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
