# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, flex, makeWrapper, php }:

stdenv.mkDerivation rec {
  name = "libphutil-${version}";
  version = "2016-09-09";

  src = fetchgit {
    url = "https://github.com/phacility/libphutil.git";
    rev = "c14343ee620e43f0ba55eaf80aabcba78c732d45";
    sha256 = "06xb9d2134a5kskq6xzyf2hj49l0ji4wkxx3mlq82c25an02bi6a";
  };

  buildInputs = [ php makeWrapper flex ];

  unpackPhase = "true";
  buildPhase = ''
    ORIG=`pwd`
    cp -R $src libphutil
    chmod +w -R libphutil
    cd libphutil/support/xhpast
    make clean all install
    cd $ORIG
  '';
  installPhase = ''
    mkdir -p $out/libexec
    cp -R libphutil $out/libexec/libphutil
  '';

  meta = {
    description = "Utility library for Phabricator";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
