# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, fetchgit, libphutil, makeWrapper, php }:

stdenv.mkDerivation rec {
  name = "arcanist-${version}";
  version = "2016-07-08";

  src = fetchgit {
    url = "https://github.com/phacility/arcanist.git";
    rev = "f1c45a3323ae20eefe29c0a22c7923fe8b151bbf";
    sha256 = "1spgnh69cghqb6lpmsf81qcx26l9bgidg909qzs2a43a4g62dz89";
  };

  buildInputs = [ php libphutil ];

  unpackPhase = "true";
  buildPhase = ''
    cp -R ${arcanist} arcanist
    chmod +w -R arcanist
  '';
  installPhase = ''
    mkdir -p $out/bin $out/libexec
    cp -R arcanist  $out/libexec/arcanist

    ln -s $out/libexec/arcanist/bin/arc $out/bin
    wrapProgram $out/bin/arc \
      --prefix PATH : "${php}/bin"
  '';

  meta = {
    description = "Command line interface to Phabricator";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
