# This file is autogenerated! Do not edit it yourself, use ../update.py for regeneration.
{ stdenv, bash, fetchgit, libphutil, makeWrapper, php }:

stdenv.mkDerivation rec {
  name = "arcanist-${version}";
  version = "2016-10-16";

  src = fetchgit {
    url = "https://github.com/phacility/arcanist.git";
    rev = "71132dbee0e2b585bdacd1481ef76eb210814139";
    sha256 = "1r7bl09bhrckc0k96689xq9qh4nxaygilspx4saf3xl5144hnxwh";
  };

  buildInputs = [ bash php libphutil makeWrapper ];

  unpackPhase = "true";
  buildPhase = ''
    cp -R $src arcanist
    chmod +w -R arcanist
  '';
  installPhase = ''
    mkdir -p $out/bin $out/libexec
    cp -R arcanist  $out/libexec/arcanist
    ln -s ${libphutil}/libexec/libphutil $out/libexec/libphutil

    ln -s $out/libexec/arcanist/bin/arc $out/bin
    wrapProgram $out/bin/arc       --prefix PATH : "${php}/bin"

    # makeWrapper ${php}/bin/php $out/bin/arc     #   --add-flags "-d include_path=${libphutil}/libexec -f $out/libexec/arcanist/scripts/arcanist.php"

    # chmod +x $out/bin/arc
  '';

  meta = {
    description = "Command line interface to Phabricator";
    homepage    = "http://phabricator.org";
    license     = stdenv.lib.licenses.asl20;
    platforms   = stdenv.lib.platforms.unix;
  };
}
